import pypsa

# Create network
n = pypsa.Network()

# Add buses with carriers
n.add("Bus", name="SlackBus", v_nom=120)
n.add("Bus", name="GenBus", v_nom=120)
n.add("Bus", name="LoadBus", v_nom=120)

# Add Slack Bus Generator (as last resort)
n.add("Generator", name="SlackGen", bus="SlackBus", p_nom=1000, control="Slack", marginal_cost=1000)
n.generators.loc["SlackGen", "p_nom_extendable"] = True  # Allow extension of p_nom if needed

# Add other generators
n.add("Generator", name="Gen1", bus="GenBus", p_nom=1000, q_min=-200, q_max=200, marginal_cost=10)

# Add Load
n.add("Load", name="Load1", bus="LoadBus", p_set=200)

# Add Transmission Lines
n.add("Line", name="Gen-Slack", bus0="GenBus", bus1="SlackBus", x=0.05, r=0.01, s_nom=1000)
n.add("Line", name="Gen-Load", bus0="GenBus", bus1="LoadBus", x=0.05, r=0.01, s_nom=1000)
n.add("Line", name="Slack-Load", bus0="SlackBus", bus1="LoadBus", x=0.05, r=0.01, s_nom=1000)

# Optimize the network
n.optimize()

# Display results
print("\nPower flow on lines (p0):")
print(n.lines_t.p0)

print("\nPower generated by each generator (p):")
print(n.generators_t.p)

print("\nPower received by the load (p):")
print(n.loads_t.p)